# Generated by Django 3.0.8 on 2020-07-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
