# Generated by Django 3.0.4 on 2020-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_member_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='insert')),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='gallery')),
            ],
        ),
    ]
