# Generated by Django 3.0.4 on 2020-07-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_nustartup'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organised',
            field=models.TextField(default='insert'),
        ),
    ]
