# Generated by Django 3.0.4 on 2020-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0007_auto_20200712_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_no', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='createevents',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
