# Generated by Django 3.0.4 on 2020-07-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0008_auto_20200712_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='last_name',
            new_name='event_name',
        ),
    ]
